# Specify version format
version: 0.2.{build}

environment:
  matrix:
    - platform: x86
      PLATFORM_DIR: Win32
      PLATFORM_OUT: 32bit
    - platform: x64
      PLATFORM_DIR: x64
      PLATFORM_OUT: 64bit

os:
  - Visual Studio 2015

install:
  - git submodule update --init --recursive
  - appveyor DownloadFile https://github.com/koolkdev/haxchi-pc-installer/releases/download/v0.1/data.zip
  - 7z x data.zip

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Release

before_build:
  - nuget restore

build:
  project: haxchi-pc-installer.sln

after_build:
  - 7z a haxchi-pc-installer-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\Release\haxchi-pc-installer.exe data

artifacts:
  - path: haxchi-pc-installer-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip

# cache nuget directory
#cache:
#  - packages -> **\packages.config

deploy:
  description: Haxchi PC Installer v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: zgIKVcub8f5Hp19YGIi0xwIaiLijYqzwF50SFD+83gpeLmZLHGZLonGEOlJAt6sc
  artifact: haxchi-pc-installer-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
